# Site settings
baseurl: "" # the subpath of your site, e.g. /blog

current_proto: "1.4.3"


# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    disable : true

languages: ["en", "ko"]
defaultLang: ko
languageNames:
  en: English
  ko: 한국어
